name: Daily Issue Metrics
on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Get dates for yesterday and today
        shell: bash
        run: |
          # Calculate yesterday's date
          yesterday=$(date -d "yesterday" +%Y-%m-%d)

          # Calculate today's date
          today=$(date +%Y-%m-%d)

          # Set an environment variable with the date range
          echo "$yesterday..$today"
          echo "yesterday=$yesterday" >> "$GITHUB_ENV"

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          SEARCH_QUERY: "repo:WilliamLindskog/github-actions-issue-insights is:issue"
          HIDE_AUTHOR: "true"
          HIDE_ITEMS_CLOSED_COUNT: "false"
          HIDE_LABEL_METRICS: "false"
          HIDE_TIME_TO_ANSWER: "false"
          HIDE_TIME_TO_CLOSE: "false"
          HIDE_TIME_TO_FIRST_RESPONSE: "false"
          IGNORE_USERS: "user1,user2"
          DRAFT_PR_TRACKING: "true"
          ENABLE_MENTOR_COUNT: "true"
          MIN_MENTOR_COMMENTS: "0"
          HIDE_LABEL_COUNT: "false"
          LABELS_TO_MEASURE: "bug,documentation,feature request,part: misc framework,part: baselines,part: communication,part: flwr-dataset,part: examples,state: open,state: resolved,state: under review,state: revision needed,state: stale,good first issue,needs clarification,needs reproduction details"
          NON_MENTIONING_LINKS: "false"
          OUTPUT_FILE: "issue_metrics.md"
          REPORT_TITLE: "Flower Issue Metrics"

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          SEARCH_QUERY: 'repo:WilliamLindskog/github-actions-issue-insights is:issue created:${{ env.yesterday }} -reason:"not planned"'

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Daily Issue Metrics Report
          token: ${{ secrets.GH_PAT }}
          content-filepath: ./daily_issue_metrics.md
          assignees: WilliamLindskog